language: php
php:
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source --dev $PREFER_LOWEST

script: vendor/bin/phpunit
